loggerLevel: Debugger
mysql:
  dsn:
  password:
  maxConnections:
  minConnections:

postgres:
  host:
  user:
  password:
  dbname:
  port: 5432
  sslmode: disable
  TimeZone: Asia/Shanghai


redis:
  host:
  db:
  password:

kafka:
  host:

chain:
  nodes:
    eth: [ ]